[package]
name = "ruian"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = { version = "0.4.38", features = ["serde"] }
csv = "1.3.0"
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
serde = { version = "1.0.203", features = ["derive"] }
zip = "2.1.3"
